language: android
sudo: required
jdk:
  - oraclejdk8

before_install:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar https://oss.sonatype.org/service/local/repositories/releases/content/com/codacy/codacy-coverage-reporter/4.0.1/codacy-coverage-reporter-4.0.1-assembly.jar

after_success:
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Kotlin -r ${TRAVIS_BUILD_DIR}/analytics-core/build/reports/jacocoTestReport/jacocoTestReport.xml --prefix analytics-core/src/main/java/

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository
  licenses:
    - android-sdk-license-.+

script:
  - ./gradlew testDebug jacocoTestReport

env:
  - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"

cache:
  directories:
    - "$HOME/.gradle/caches/jars-1"
    - "$HOME/.gradle/daemon"
    - "$HOME/.gradle/native"
    - "$HOME/.gradle/wrapper"